export const errorDictionary = {
    'PRODUCT_NOT_FOUND': 'El Producto no ha sido encontrado',
    'USER_NOT_FOUND': 'El Usuario no ha sido encontrado',
    'PRODUCT_CREATION_ERROR': 'Error al crear el producto',
    'ADD_TO_CART_ERROR': 'Error al agregar el producto al carrito',
    'INVALID_PRODUCT_DATA': 'Los datos del producto son inválidos',
    'AUTHENTICATION_ERROR': 'Error de autenticación. Verifica tus credenciales.',
    'UNAUTHORIZED_ACCESS': 'Acceso no autorizado. Inicia sesión para continuar.',
    'DATABASE_CONNECTION_ERROR': 'Error de conexión a la base de datos',
    'UNEXPECTED_ERROR': 'Ha ocurrido un error inesperado. Inténtalo de nuevo más tarde.',
    'INVALID_DATA_FORMAT': 'Formato de datos no válido',
    'CART_OPERATION_ERROR': 'Error en la operación del carrito',
    'CART_CREATION_ERROR' : 'Error al crear el carrito',
    'CART_NOT_FOUND' : 'El carrito no ha sido encontrado',
    'CART_DELETE_PRODUCT' : 'Error al eliminar los productos del carrito',
    'FAILE_TO_EMAIL' : 'Error al enviar el correo electrónico',
    'MESSAGE_ERROR' : 'Error al obtener el mensaje',
    'INVALID_EMAIL' : 'Correo electrónico no válido',
    'MESSAGE_IS_VERY_LONG' : 'El mensaje es demasiado largo',
    'ERROR_TO_SAVE_MESSAGE' : 'Error alguarda el mensaje',
    'CREDENTIALS_ERROR' : 'Password o Email incorrectos',
    'ERROR_TO_CREATE_USER' : 'Error al crear el usuario',
    'ERROR_TO_UPDATE_PRODUCT' : 'Error al actualizar el producto',
    'ERROR_DELETE_PRODUCT' : 'Error al eliminarl el producto',
    'ACCESS_DANIED' : 'No tienes permiso para realizar esta acción',
    'ERROR_SIMULATING_PRODUCTS' : 'Error al generar productos simulados',
    'USER_ALREADY_EXISTS' : 'El usuario ya existe',

};